config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login' => 'pages#login'
  root 'pages#login'
  post '/login' => 'pages#new_session'
  get '/logout' => 'pages#logout'
  resources :users
  resources :cohorts do
    resources :batches, only: [:create, :show]
    resources :students, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batch.rb
class Batch < ApplicationRecord
  has_many :groups
  belongs_to :cohort
  has_many :students, through: :cohort
  delegate :history, to: :cohort
  attr_reader :size

  validates :size, presence: true, if: :new_record?
  after_create :populate_groups

  def size=(a)
    @size = a.to_i
  end

  def students
    self.cohort.students.order(name: :asc)
  end

  def populate_groups
    groups = get_groups(students)
    groups.each do |group|
      self.groups.create(students: group)
    end
  end

  def get_groups(people)
    return [people] if self.size > people.length
    groups_enum(people).each do |group|
      new_people = people - group
      return [group] if new_people.length == 0
      other_groups = get_groups(new_people)
      next unless other_groups
      return [group] + other_groups
    end
    false
  end

  def sort_rank(*group)
    return 0 if group.length == 0
    return self.history.count {|past_group| past_group.to_a.include?(group[0])} if group.length == 1

    group.sort.combination(2).reduce(0) { |sum, pair| sum + self.history.count {|past_group| past_group & pair == pair} }
  end

  def groups_enum(people)
    Enumerator.new do |y|
      history = self.history.map(&:dup)

      until people.empty?
        next_group = []
        until next_group.length == self.size || people.empty?
          people = people.sort {|a,b| self.sort_rank(*next_group, b) <=> self.sort_rank(*next_group, a)}
          next_group << people.find {|person| !next_group.include?(person)}
        end
        history << next_group
        y << next_group
      end
    end
  end
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  belongs_to :user
  has_many :students
  has_many :batches
  has_many :groups, through: :batches

  def history
    self.groups.map do |group|
      group.students
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_students
  has_many :students, through: :group_students

  def <<(new_student)
    self.students << new_student
  end
end

app/models/group_student.rb
class GroupStudent < ApplicationRecord
  belongs_to :group
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :cohort
  has_many :group_students
  has_many :groups, through: :group_students

  validates :name, presence: true, uniqueness: {scope: :cohort}

  def ==(other)
    self.id == other.id
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :cohorts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def login?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  def index
  end

  def show
    @batch = Batch.find(params[:id])
    @groups = @batch.groups
  end

  def new
  end

  def edit
  end

  def create
    @cohort = Cohort.find(params[:cohort_id])
    batch = @cohort.batches.create(batch_params)
    redirect_to [@cohort, batch]
  end

  def update
  end

  def destroy
  end

  protected
  def batch_params
    params.require(:batch).permit(:size)
  end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def index
    @cohorts = current_user.cohorts
  end

  def show
    @cohort = Cohort.find(params[:id])
    @students = @cohort.students
  end

  def new
    @cohort = current_user.cohorts.new
  end

  def edit
  end

  def create
    @cohort = Cohort.new(cohort_params)

    if @cohort.save
      redirect_to @cohort
    else
      render 'new'
    end
  end

  def update
  end

  def destroy
  end

  private
  def cohort_params
    params.require(:cohort).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def login
    redirect_to '/cohorts' if login?
  end

  def new_session
    @user = User.find_by_username(params[:login]) || User.find_by_email(params[:login])
    if @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/cohorts'
    else
      render 'login'
    end
  end

  def logout
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

  before_action :get_cohort
  protected

  def get_cohort
    @cohort = Cohort.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/batches/show.html.erb
<h1><%= @batch.created_at %></h1>

<ul>
<% @groups.each do |group| %>
  <li>
    <%= group.students.map(&:name).join(', ') %>
  </li>
<% end %>
</ul>
<%= link_to 'back', @batch.cohort %>

app/views/cohorts/index.html.erb
<h1>Cohorts</h1>
<%= link_to 'Add new cohort', new_cohort_path %>
<ul>
<% @cohorts.each do |cohort| %>
  <li>
  <%= link_to cohort.name, cohort_path(cohort.id) %>
  </li>
<% end %>
</ul>

app/views/cohorts/new.html.erb
<%= form_for @cohort, url: {action: "create"} do |f| %>
  <%= f.text_field :name %>
  <%= f.submit 'Add new cohort' %>
<% end %>

app/views/cohorts/show.html.erb
<h1><%= @cohort.name %></h1>

<ul>
<% @students.each do |student| %>
  <li>
    <%= student.name %>
  </li>
<% end %>
</ul>

<h2>Batches</h2>
<ul>
<% @cohort.batches.each do |batch| %>
  <li>
    <%= link_to batch.created_at.to_s, [@cohort, batch] %>
  </li>
<% end %>
</ul>

<%= form_tag cohort_batches_path(@cohort), method: 'post' do %>
  <%= submit_tag "Make a new batch with groups of..." %>
  <!-- <%= label_tag :n, "People per group:" %> -->
  <%= select_tag :'batch[size]', options_for_select([['2', 2],['3', 3],['4',4],['5',5]],1) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupGenerator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/login.html.erb
<%= form_tag '/login', method: 'post' do %>
  <%= label_tag :login, 'Username or email' %>
  <%= text_field_tag :login %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= submit_tag 'Login' %>
<% end %>